# Generated by Django 2.0.13 on 2020-01-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywordsearch',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('search_url', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'keywordsearch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
